# Generated by Django 4.2.20 on 2025-04-20 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('layout', models.JSONField(default=dict, verbose_name='layout')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dashboard',
                'verbose_name_plural': 'dashboards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('widget_type', models.CharField(choices=[('chart', 'Chart'), ('counter', 'Counter'), ('table', 'Table'), ('status', 'Status')], max_length=20, verbose_name='widget type')),
                ('configuration', models.JSONField(default=dict, verbose_name='configuration')),
                ('data_source', models.CharField(max_length=255, verbose_name='data source')),
                ('refresh_interval', models.PositiveIntegerField(default=60, help_text='Refresh interval in seconds', verbose_name='refresh interval')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dashboard widget',
                'verbose_name_plural': 'dashboard widgets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='is favorite')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dashboard.dashboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user dashboard',
                'verbose_name_plural': 'user dashboards',
                'ordering': ['user', '-is_favorite', 'dashboard'],
                'unique_together': {('user', 'dashboard')},
            },
        ),
        migrations.CreateModel(
            name='DashboardWidgetInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.PositiveIntegerField(verbose_name='position x')),
                ('position_y', models.PositiveIntegerField(verbose_name='position y')),
                ('width', models.PositiveIntegerField(verbose_name='width')),
                ('height', models.PositiveIntegerField(verbose_name='height')),
                ('configuration_override', models.JSONField(blank=True, default=dict, verbose_name='configuration override')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_instances', to='dashboard.dashboard')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='dashboard.dashboardwidget')),
            ],
            options={
                'verbose_name': 'dashboard widget instance',
                'verbose_name_plural': 'dashboard widget instances',
                'ordering': ['dashboard', 'position_y', 'position_x'],
                'unique_together': {('dashboard', 'position_x', 'position_y')},
            },
        ),
    ]
