# Generated by Django 4.2.20 on 2025-04-21 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('content', models.JSONField(default=dict, verbose_name='content')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('ppt', 'PowerPoint'), ('html', 'HTML'), ('markdown', 'Markdown')], max_length=20, verbose_name='format')),
                ('file', models.FileField(blank=True, null=True, upload_to='analysis_reports/', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'analysis report',
                'verbose_name_plural': 'analysis reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('analysis_type', models.CharField(choices=[('longitudinal', 'Longitudinal'), ('horizontal', 'Horizontal')], max_length=20, verbose_name='analysis type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('results', models.JSONField(blank=True, default=dict, verbose_name='results')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds', null=True, verbose_name='execution time')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_analysis_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'analysis task',
                'verbose_name_plural': 'analysis tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('visualization_type', models.CharField(choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('scatter', 'Scatter Plot'), ('pie', 'Pie Chart'), ('heatmap', 'Heatmap'), ('box', 'Box Plot'), ('histogram', 'Histogram')], max_length=20, verbose_name='visualization type')),
                ('configuration', models.JSONField(default=dict, verbose_name='configuration')),
                ('data', models.JSONField(default=dict, verbose_name='data')),
                ('image', models.ImageField(blank=True, null=True, upload_to='visualizations/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visualizations', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='analysis.analysistask')),
            ],
            options={
                'verbose_name': 'visualization',
                'verbose_name_plural': 'visualizations',
                'ordering': ['task', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('expression', models.TextField(verbose_name='expression')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_validation_rules', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='analysis.analysistask')),
            ],
            options={
                'verbose_name': 'validation rule',
                'verbose_name_plural': 'validation rules',
                'ordering': ['task', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('source_type', models.CharField(choices=[('file', 'File'), ('database', 'Database'), ('api', 'API')], max_length=20, verbose_name='source type')),
                ('file_format', models.CharField(blank=True, choices=[('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON'), ('xml', 'XML'), ('blf', 'BLF'), ('h5', 'H5'), ('mdf', 'MDF'), ('mat', 'MAT')], max_length=20, null=True, verbose_name='file format')),
                ('file', models.FileField(blank=True, null=True, upload_to='data_sources/', verbose_name='file')),
                ('connection_string', models.CharField(blank=True, max_length=255, verbose_name='connection string')),
                ('api_url', models.URLField(blank=True, verbose_name='API URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_data_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'data source',
                'verbose_name_plural': 'data sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataCleaningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('rule_type', models.CharField(choices=[('global', 'Global'), ('local', 'Local')], default='global', max_length=20, verbose_name='rule type')),
                ('configuration', models.JSONField(default=dict, verbose_name='configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cleaning_rules', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_rules', to='analysis.analysistask')),
            ],
            options={
                'verbose_name': 'data cleaning rule',
                'verbose_name_plural': 'data cleaning rules',
                'ordering': ['task', 'rule_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('pipeline_config', models.JSONField(default=dict, verbose_name='pipeline configuration')),
                ('is_global', models.BooleanField(default=False, help_text='If true, this template is available to all users', verbose_name='is global')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_analysis_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'analysis template',
                'verbose_name_plural': 'analysis templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisTaskDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='analysis.datasource')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='analysis.analysistask')),
            ],
            options={
                'verbose_name': 'analysis task data source',
                'verbose_name_plural': 'analysis task data sources',
                'ordering': ['-added_at'],
            },
        ),
    ]
