# Generated by Django 4.2.20 on 2025-04-21 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '__first__'),
        ('analysis', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_tasks', to='projects.project'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='analysis.analysistemplate'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_tasks', to='testcases.testcase'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_analysis_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='analysis.analysistask'),
        ),
        migrations.AlterUniqueTogether(
            name='analysistaskdatasource',
            unique_together={('task', 'data_source')},
        ),
    ]
